### ISSUE TITLE
PCB n00b question

### ISSUE THREAD

**Issue by jcfergus** [insom/learn-to-solder#1]
Hi, Aaron - This is awesome, thanks for creating it!  I'm working on customizing it a little bit to get some created for an event I'm doing at my kids' school, but am new to PCB design.  My question is, I'd like to mount the battery holder and the pin on the back side, so I can put a logo on the front side, along with the switch and LEDs.  I'm just trying to figure out if I need to do anything special with the pads to make it so if I solder them on the opposite side from your assembly they are conductive through the holes.  (Or if I need to move the traces from the pads to the back and create vias to connect them to the front.)  

Thanks in advance for helping out a n00b.  😃

**Comment by insom** [comment]
Hi Justin,

It's great to hear that this project is a basis for your own badges!

All the holes on my existing design are plated through-hole -- if you get them made at a board house that means they will be internally plated and connected on both sides. I've also made sure that there are solder pads on both sides of the holes. I wanted to allow for maximum flexibility so each component can be soldered from either side. You shouldn't need to move any connections to the other side of the board or worry about vias.

I hope that helps.

**Comment by jcfergus** [comment]
Awesome.  That's how I -thought- I was interpreting the diagram and your photos, but wanted to be 100% sure before I sent off orders that I probably wouldn't have time to re-do if I screwed it up.  Thanks!
